# Generated by Django 6.0.4 on 2026-05-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='presentation_file',
            field=models.FileField(blank=True, null=True, upload_to='presentations/'),
        ),
    ]
